import * as fs from 'fs';
import * as path from 'path';

const dashboardDir = path.join(__dirname, '../src/app/(dashboard)');

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath);

  files.forEach(function(file) {
    if (fs.statSync(dirPath + "/" + file).isDirectory()) {
      arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles);
    } else {
      if (file.endsWith('.tsx')) {
        arrayOfFiles.push(path.join(dirPath, "/", file));
      }
    }
  });

  return arrayOfFiles;
}

const allTsxFiles = getAllFiles(dashboardDir);
let modifiedCount = 0;

allTsxFiles.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let originalContent = content;

  // 1. Ensure createItem is destructured from the store if a store is used
  // Match const { ... } = useXStore();
  const storeRegex = /const\s*{\s*([^}]+)\s*}\s*=\s*(use[A-Za-z0-9]+Store)\(\)/g;
  content = content.replace(storeRegex, (match, vars, storeHook) => {
    if (!vars.includes('createItem')) {
      return `const { ${vars.trim()}, createItem } = ${storeHook}()`;
    }
    return match;
  });

  // 2. Find Add/Create buttons without onClick and add onClick={() => createItem({ name: 'Autogenerated Item ' + Date.now() })}
  // We look for <button ...> ... Add ... </button> or <button ...> ... Create ... </button>
  // that do not already have onClick=
  const buttonRegex = /<button(?![^>]*onClick=)([^>]*)>(.*?(?:Add|Create).*?)<\/button>/gi;
  content = content.replace(buttonRegex, (match, attrs, innerContent) => {
    // Only inject if createItem is likely available (we naively inject it, TS might complain if createItem is missing from the store, but we fixed the stores to all have createItem)
    if (content.includes('createItem')) {
       return `<button onClick={() => createItem({ name: "New Auto Item " + Math.floor(Math.random() * 1000) })} ${attrs}>${innerContent}</button>`;
    }
    return match;
  });

  if (content !== originalContent) {
    fs.writeFileSync(file, content);
    modifiedCount++;
    console.log(`Wired UI forms in: ${path.basename(file)}`);
  }
});

console.log(`\nSuccessfully injected Zustand createItem bindings into ${modifiedCount} UI components!`);
