plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\asus\\OneDrive\\Desktop\\ConstructOs\\temp_deploy"
publishOrigin = "default"
base = "C:\\Users\\asus\\OneDrive\\Desktop\\ConstructOs\\temp_deploy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]